### ISSUE TITLE
Steem key field suggests posting key, not active key

### ISSUE THREAD

**Issue by Smittyvb** [steemit/wallet#10]
![image](https://user-images.githubusercontent.com/10530973/54198489-01aa4100-449d-11e9-93e9-178141f74292.png)
Bottom field should suggest to use a Active key, not a Posting key.

**Comment by jredbeard** [comment]
Since users may login just to 'claim rewards', a posting key is still a sufficient thing to suggest here. Login with the active key is now allowed also though.
