### ISSUE TITLE
Should Redisplay Wallet Page After Successful Log-in (Mobile Viewport)

### ISSUE THREAD

**Issue by eastmaels** [steemit/wallet#15]
#### Expected behavior

When logging in from the wallet page (mobile viewport), it should redirect to the wallet page upon successful login - the same behavior when logging in from the home page.

#### Actual behavior
User successfully logs in, but does not display the wallet page.

#### How to reproduce

1. Log-out of SteemitWallet
1. Go to your steemit wallet page (i.e., https://steemitwallet.com/@username/transfers)
1. On the top-right hamburger menu, click on **Sign in**
1. Enter your username and active key
1. Click Login

#### Result

You were successfully logged in, but the log-in pop-up/page is still displayed and does not redirect you to your wallet/transfers page.

* Browser version: Chrome 73.0.3683.86 (Official Build) (64-bit)
* Operating system: Mac OSX 10.11.6

#### Recording Of The Bug

Login from Mobile Wallet Page (BUG) | Login from Home Page (Expected Behavior)
-- | --
![bug-does-not-load-wallet-on-mobile-login.gif](https://ipfs.busy.org/ipfs/QmVwhzHQM2hVtW8aiyQphdaNWzPkr73fpbgeEyZ7wXNiyD) | ![login-on-steemitwallet-home.gif](https://ipfs.busy.org/ipfs/QmZYvkf11yjmWKYDQtAvPXoJnTFfkudkh8onGit7VyNAgH)

**Comment by roadscape** [comment]
Thanks for the report. This seems to be the same issue as #24 and there is a pending fix.
