### ISSUE TITLE
All Witness Threads *Are* External

### ISSUE THREAD

**Issue by inertia186** [steemit/wallet#23]
*As a regular user, I'd like a better indication when a witness url will lead away from the wallet (even if the url links to steemit.com), so I know I'm still about to leave the wallet.*

https://github.com/steemit/wallet/blob/b815663c11841400c99e814762fb1f34770e2299/src/app/components/pages/Witnesses.jsx#L120-L135

In addition, the URL may start with `https://steemit.com` but is always re-written to become `https://steemitwallet.com/` leading to a 404.

![image](https://user-images.githubusercontent.com/494368/56088283-0cf0e380-5e32-11e9-9f64-0faed4b7fd5b.png)

Also, it might be wise to sanitize the url for witnesses like netuoso who set it to something invalid:

https://steemd.com/@netuoso

![image](https://user-images.githubusercontent.com/494368/56088276-dc10ae80-5e31-11e9-8d9f-e375fd2e23d4.png)

**Comment by roadscape** [comment]
Addressed in https://github.com/steemit/wallet/pull/47
