### ISSUE TITLE
On chrome/android the suggested key login is not appearing

### ISSUE THREAD

**Issue by jredbeard** [steemit/wallet#25]
When logging in on chrome desktop, or iOS/Safari, the wallet suggests that you login with your posting key. On android/chrome, it only says "Password or WIF" without a suggestion.

![Screen Shot 2019-04-15 at 3 49 34 PM](https://user-images.githubusercontent.com/23157604/56160796-16935c00-5f96-11e9-8b17-6bdf028b3b6a.png)

**Comment by roadscape** [comment]
Possibly tied to https://github.com/steemit/wallet/issues/24
