### ISSUE TITLE
Public Profile Settings: Image Uploading and Keys

### ISSUE THREAD

**Issue by gryter** [steemit/wallet#28]
While uploading a profile picture via steemitwallet, logged in with active key:
![image](https://user-images.githubusercontent.com/31012685/56385687-e0e8b000-61ed-11e9-808d-b174b1cacef6.png)

Upon "Update" gives missing authority error, requiring active key.

To resolve one must login with posting key, upload into field, then logout, login with active key, click 'update' to transmit. While the userbase seems to have figured this out by trial and error, it is less than ideal. 

Removing the Upload option and allowing only existing links may be a temporary solution.

**Comment by roadscape** [comment]
There is a proposal to make `json_metadata` editable with posting key. If that is applied (requiring HF) we can move these settings back to social and this will be a non-issue.

**Comment by jredbeard** [comment]
This change also requires an update to imagehoster to allow an active authority to generate the signature used to authenticate for uploading images.

I have this work on a PR for imagehoster here: https://github.com/steemit/imagehoster/pull/104
