### ISSUE TITLE
Bug in power down message

### ISSUE THREAD

**Issue by sakibarifin** [steemit/wallet#29]
**Expected behavior**

Power down message should say 
> The next power down is scheduled to happen in X days.

**Actual behavior**
Power down message says something wrong when logged out.

> The next power down is scheduled to happen  in 87 years.

> ![image](https://user-images.githubusercontent.com/33556544/56441476-d4fd0b00-631f-11e9-9a6b-d1fce684a365.png)

**Steps to reproduce**

1. Visit steemit wallet when logged out. https://steemitwallet.com/@sakibarifin/transfers
2. Scroll down to view the power down message

**Comment by roadscape** [comment]
Note: This is a steemd bug, fix in progress
