### ISSUE TITLE
community creation

### ISSUE THREAD

**Issue by roadscape** [steemit/wallet#68]
Creation process:

1. User fills out a form with the following fields:
   - `title`: up to 32 characters
   - `about`: short summary of community, up to 120 characters
   - `is_nsfw`: checkbox to be checked if contents will be nsfw
2. allocate an account name of a specific format:
   1. `/^hive-1\d{5}$/` (prefix `hive-1` and add 5 digits)
   2. use a random number; do not handle collisions
3. generate new master password, verify user saved it properly
4. submit `account_create`, wait for confirmation, then submit `custom_json` ops:
   1. `setRole` with `{community, account, role: 'admin'}`
   2. `updateProps` with `{community, props: {title, about, is_nsfw}}`
   3. for `account` use the creator's account name
   4. for `community` use newly created `hive-1xxxxx` name
   5. the ops must be signed by the new account (**not** by the logged in user)
5. show success message and link to `https://steemitdev.com/trending/<account_name>`

**Comment by Smittyvb** [comment]
> The user will need to have account_creation_fee STEEM available in their account. Currently this is 3 STEEM.

RC-based creation is also possible.

**Comment by Smittyvb** [comment]
> The PDF would also contain a 4 or 5 digit PIN which would have to be re-entered into the UI to confirm that it was saved/read.

It would be confusing to have a PDF containing a PIN number only used during creation. Wouldn't "verify by entering your active key" be better?

**Comment by roadscape** [comment]
> RC-based creation is also possible.

This can be added later 👍 

> Wouldn't "verify by entering your active key" be better?

Agreed, updated

**Comment by roadscape** [comment]
https://github.com/steemit/wallet/pull/86

**Comment by roadscape** [comment]
https://github.com/steemit/wallet/pull/96
